import { League_Spartan } from "next/font/google";
import "./globals.css";

const league_Spartan = League_Spartan({ subsets: ["latin"] });

export const metadata = {
  title: "Frontend Mentor | Social proof section",
  description: "Generated by Anass GOUZGAR",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={league_Spartan.className}>{children}</body>
    </html>
  );
}
